# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d57adef1226e02c5bac38afb784bb7e404d94b0aed2ed0b95c3f056b07d75eceba269a479a13d925b778eedfc7327e25b4087d4a16bf1179a54cb13af4a852

test:
  secret_key_base: fb16d0235ec36c06a72f62aeb8895ec8ce4f652a05ac45963db36aa08936a0cb1ab466c0cdacda3559b538ca1221e2f406adddfd1f77964ab7b16b3ef910b718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
